### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by odedhb** [enkidoo-ai/xml2json#1]
`xmlStr = xmlStr.replace(/ {1,}<|\t{1,}</g, '<'); //replace leading spaces and tabs`

```
RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at cleanXML (/Users/oded/Documents/GitHub/snw/ctv-server/node_modules/xml2json-light/xml2json.js:67:21)
    at xml2json (/Users/oded/Documents/GitHub/snw/ctv-server/node_modules/xml2json-light/xml2json.js:11:14)
    at xml2jsonRecurse (/Users/oded/Documents/GitHub/snw/ctv-server/node_modules/xml2json-light/xml2json.js:38:23)
    at xml2json (/Users/oded/Documents/GitHub/snw/ctv-server/node_modules/xml2json-light/xml2json.js:12:12)
    at xml2jsonRecurse (/Users/oded/Documents/GitHub/snw/ctv-server/node_modules/xml2json-light/xml2json.js:38:23)
    at xml2json (/Users/oded/Documents/GitHub/snw/ctv-server/node_modules/xml2json-light/xml2json.js:12:12)
    at xml2jsonRecurse (/Users/oded/Documents/GitHub/snw/ctv-server/node_modules/xml2json-light/xml2json.js:38:23)
    at xml2json (/Users/oded/Documents/GitHub/snw/ctv-server/node_modules/xml2json-light/xml2json.js:12:12)
    at xml2jsonRecurse (/Users/oded/Documents/GitHub/snw/ctv-server/node_modules/xml2json-light/xml2json.js:38:23)

```

Caused by this XML:

```


<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:media="http://search.yahoo.com/mrss/">
<channel>
  <title><![CDATA[WatchMojo.com ]]></title>
  <link>http://www.watchmojo.com</link>
  <description>WatchMojo.com: Producer, Publisher and Syndicator of Video Content for Web, Wireless, Digital Out of Home Networks and Television.</description>
  <language>en-us</language>
  <image>
    <title><![CDATA[WatchMojo.com ]]></title>
    <width>144</width>
    <height>60</height>
    <link>http://www.watchmojo.com</link>
    <url>http://www.watchmojo.com/newsite/images/logo_144.png</url>
  </image> 
  <copyright><![CDATA[2010, Watchmojo.com]]></copyright> 
  <item>
    <title><![CDATA[Top 10 Times Superman Was Forced to Take a Life]]></title>
    <link>http://www.watchmojo.com/video/id/21963/</link>
    <pubDate>Thu, 31 May 2018 20:45:59 +0000</pubDate>
    <guid>WM-CB-Top10-Moments-Where-Superman-Kills_U0G4Z2-720p30</guid>
    <media:title><![CDATA[Top 10 Times Superman Was Forced to Take a Life]]></media:title>
    <media:description type="html"><![CDATA[He has pledged to never take a life…but has he kept his word? Welcome to WatchMojo.com, and today we’re counting down the Top 10 Moments Where Superman Kills.
 
For this list, we’re looking at moments throughout Superman’s comic books history in which he, intentionally or not, killed another living being. We are including Elseworlds stories, alternate world stories, etc.]]></media:description>
    <media:keywords><![CDATA[Comics, Comic Books, Superhero, DC Comics, Superman, Craig Butler]]></media:keywords>
    <media:category><![CDATA[Comic]]></media:category>     
    <media:content url="http://s3.amazonaws.com/watchmojo-640/8ef9ff1745010052553a0cbd222d1cfe.mp4"  type="video/mp4" width="640" height="360" />    
    <media:thumbnail url="http://s3.amazonaws.com/watchmojo-files/images/mojothumbs/WM-CB-Top10-Moments-Where-Superman-Kills_U0G4Z2-720p30_100.jpg" width="100" height="57"/>    
    <media:text type="html"><![CDATA[Written by Craig Butler

He has pledged to never take a life…but has he kept his word? Welcome to WatchMojo.com, and today we’re counting down the Top 10 Moments Where Superman Kills.
 
For this list, we’re looking at moments throughout Superman’s comic books history in which he, intentionally or not, killed another living being. We are including Elseworlds stories, alternate world stories, etc.

Have an idea you want to see made into a WatchMojo video? Check out our suggest page at http://watchmojo.com/suggest and submit your idea.]]></media:text>
	<media:credit>Adrian Sousa</media:credit>
  </item>
</channel>
</rss>


```

**Comment by monkpit** [comment]
I get the same error on a different bit of xml - when I rewrite my XML without any ":" characters in the element names, it works. So it looks like this package just barfs on the colon character.

**Comment by monkpit** [comment]
If I take my xml string and before I parse, naively run `xmlString.replace(/:/g, '');`, then I don't get the error anymore.

Obviously you shouldn't do this because it will alter anything in the entire XML that contains a colon. But it proves that the colon is the problem here.

**Comment by xqin** [comment]
same issue.

xml2json-light@1.0.6

```
const { xml2json } = require('xml2json-light');

const a = `
<scm>
<scms>
  <hudson.plugins.git.GitSCM plugin="git@4.0.0-rc">
    <userRemoteConfigs>
      <hudson.plugins.git.UserRemoteConfig>
        <url>https://www.google.com/ncr</url>
      </hudson.plugins.git.UserRemoteConfig>
    </userRemoteConfigs>
  </hudson.plugins.git.GitSCM>
</scms>
</scm>`;

xml2json(a);
```


```
    xmlStr = xmlStr.replace(/ {1,}<|\t{1,}</g, '<'); //replace leading spaces and tabs
                    ^

RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at cleanXML (/path/to/workspace/node_modules/xml2json-light/xml2json.js:67:21)
    at xml2json (/path/to/workspace/node_modules/xml2json-light/xml2json.js:11:14)
    at xml2jsonRecurse (/path/to/workspace/node_modules/xml2json-light/xml2json.js:38:23)
    at xml2json (/path/to/workspace/node_modules/xml2json-light/xml2json.js:12:12)
    at xml2jsonRecurse (/path/to/workspace/node_modules/xml2json-light/xml2json.js:38:23)
    at xml2json (/path/to/workspace/node_modules/xml2json-light/xml2json.js:12:12)
    at xml2jsonRecurse (/path/to/workspace/node_modules/xml2json-light/xml2json.js:38:23)
    at xml2json (/path/to/workspace/node_modules/xml2json-light/xml2json.js:12:12)
    at xml2jsonRecurse (/path/to/workspace/node_modules/xml2json-light/xml2json.js:38:23)
```

**Comment by fmalk** [comment]
I have an insight I'll share here, in case someone else comes searching for this issue:

That "Maximum call stack size exceeded" means the lib is stuck in a loop. Look for XML tags with the same name in diferent context, usually one inside another.
The OP has this problem: <item> has <title> and <media:title> -- if "media:" is ignored (which usually namespaces are) then you have two identical tags <title> inside <item>. This leads to problems for parsing. It "solved" the bug by replacing colons, so the tag would become <mediatitle> and it goes away.

**Comment by fmalk** [comment]
Previous comment parsed some code I was typing, but I ended it by saying it would become an "mediatitle" tag

**Comment by monkpit** [comment]
@fmalk the fix is already implemented (but not merged) to allow any char except space in a tag. See the open PR (from 2018) for details.

**Comment by fmalk** [comment]
@monkpit what I was describing isn't related to chars in tags, it's about malformed (or ill-thought) XMLs which allows for tags with same names in the same context. For example, the following XML will break under this lib:
```
<root>
    <travel>
         <travel>Vacation</travel>
         <date>2020-08-25</date>
    </travel>
</root>
```

"travel" is both a node and a leaf, this lib doesn't handle this edge case well, and in the end is about malformed XML.
